#!/usr/bin/env node

const chalk = require('chalk')
const fs = require('fs')

countlines()

function countlines(path = process.argv[2]) {
  fs.readFile(path, { encoding: 'utf-8' }, (err, data) => {
    if (err) {
      console.error(chalk.red(err))
    } else {
      console.log(chalk.green(data.split('\n').length))
    }
  })
}
